package controller

import (
	"context"
	stderrors "errors"
	"time"

	policyAPI "github.com/giantswarm/policy-api/api/v1alpha1"
	kyvernov1 "github.com/kyverno/kyverno/api/kyverno/v1"
	kyvernov2 "github.com/kyverno/kyverno/api/kyverno/v2"
	"k8s.io/apimachinery/pkg/api/errors"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"sigs.k8s.io/controller-runtime/pkg/client"
	"sigs.k8s.io/controller-runtime/pkg/log"
)

var DefaultRequeueDuration = (time.Minute * 5)

// PolicyCacheMissRequeueDuration is how long to wait before retrying a
// PolicyManifest whose ClusterPolicy is not in the cache yet. The cache is
// filled by the ClusterPolicy controller, so a miss is normally a transient
// start-up race rather than an error.
var PolicyCacheMissRequeueDuration = (time.Second * 10)

const (
	ComponentName = "kyverno-policy-operator"
	ManagedBy     = "app.kubernetes.io/managed-by"
	GSPolicy      = "policy.giantswarm.io/policy"
	MaxNameLength = 58

	LabelSource                  = "policy.giantswarm.io/source"
	SourceGSPolex                = "gspolex"
	SourceExceptionRecommender   = "exception-recommender"
	SourceChartOperator          = "chart-operator"
	AnnotationMigratedFrom       = "policy.giantswarm.io/migrated-from"
	AnnotationUnresolvedPolicies = "policy.giantswarm.io/unresolved-policies"
)

// generateLabels generates the labels for the Kyverno Policy Exception.
func generateLabels() map[string]string {
	labels := map[string]string{
		ManagedBy: ComponentName,
		GSPolicy:  "",
	}
	return labels
}

// setManagedLabels marks obj as generated by KPO from the given source, keeping other labels.
func setManagedLabels(obj metav1.Object, source string) {
	labels := obj.GetLabels()
	if labels == nil {
		labels = map[string]string{}
	}
	for k, v := range generateLabels() {
		labels[k] = v
	}
	labels[LabelSource] = source
	obj.SetLabels(labels)
}

// setAnnotation sets key to value, or removes it when value is empty.
func setAnnotation(obj metav1.Object, key, value string) {
	annotations := obj.GetAnnotations()
	if value == "" {
		delete(annotations, key)
		obj.SetAnnotations(annotations)
		return
	}
	if annotations == nil {
		annotations = map[string]string{}
	}
	annotations[key] = value
	obj.SetAnnotations(annotations)
}

// isMigrated reports whether exception-recommender created this gspolex from a legacy PolicyException.
func isMigrated(p *policyAPI.PolicyException) bool {
	_, ok := p.Annotations[AnnotationMigratedFrom]
	return ok
}

// sourceOf reports the policy.giantswarm.io/source value for an exception generated from p.
func sourceOf(p *policyAPI.PolicyException) string {
	if isMigrated(p) {
		return SourceExceptionRecommender
	}
	return SourceGSPolex
}

// errNotManaged stops KPO from changing an object with a generated name that someone else created.
var errNotManaged = stderrors.New("object exists and is not managed by kyverno-policy-operator, leaving it unchanged")

// checkManaged returns errNotManaged for an existing object without KPO's managed-by label. Call it
// first in a CreateOrUpdate mutate function, so nothing is written.
func checkManaged(obj metav1.Object) error {
	if obj.GetResourceVersion() != "" && obj.GetLabels()[ManagedBy] != ComponentName {
		return errNotManaged
	}
	return nil
}

// applyFailedReason is the generation error reason for a failed CreateOrUpdate.
func applyFailedReason(err error) string {
	if stderrors.Is(err, errNotManaged) {
		return "name_taken"
	}
	return "apply_failed"
}

// deleteManaged deletes obj if it exists and KPO manages it. Objects KPO did not create are never touched.
func deleteManaged(ctx context.Context, c client.Client, obj client.Object) error {
	logger := log.FromContext(ctx)
	key := client.ObjectKeyFromObject(obj)

	if err := c.Get(ctx, key, obj); err != nil {
		if errors.IsNotFound(err) {
			logger.V(1).Info("nothing to delete", "object", key)
			return nil
		}
		logger.Error(err, "failed to get object for deletion", "object", key)
		return err
	}

	if obj.GetLabels()[ManagedBy] != ComponentName {
		logger.V(1).Info("object not managed by kyverno-policy-operator, leaving alone", "object", key)
		return nil
	}

	if err := c.Delete(ctx, obj); err != nil {
		if errors.IsNotFound(err) {
			return nil
		}
		logger.Error(err, "failed to delete object", "object", key)
		return err
	}
	logger.Info("deleted managed object", "object", key)
	return nil
}

// translateTargetsToResourceFilters takes a Giant Swarm Policy API target array and creates the necessary Kyverno ResourceFilters
func translateTargetsToResourceFilters(targets []policyAPI.Target) kyvernov1.ResourceFilters {
	resourceFilters := kyvernov1.ResourceFilters{}
	for _, target := range targets {
		translatedResourceFilter := kyvernov1.ResourceFilter{
			ResourceDescription: kyvernov1.ResourceDescription{
				Namespaces: target.Namespaces,
				Names:      formatNames(target.Names),
				Kinds:      generateExceptionKinds(target.Kind),
			},
		}
		resourceFilters = append(resourceFilters, translatedResourceFilter)
	}
	return resourceFilters
}

// formatName validates the names size and adds a wildcard if necessary
func formatNames(names []string) []string {
	newNames := []string{}
	for _, name := range names {
		// Check if name will be truncated by Kubernetes
		if len(name) > MaxNameLength {
			// Truncate in advanced to avoid issues
			name = truncateName(name)
		}
		// Append wildcard if needed
		name = addNameWildcard(name)
		// Append name to the newNames array
		newNames = append(newNames, name)
	}
	return newNames
}

// truncateName truncates a string name to 58 characters to match Kubernetes limits on generated resources
func truncateName(name string) string {
	return name[:MaxNameLength]
}

// addNameWildcard appends a wildcard to a target name if it does not already have one.
func addNameWildcard(name string) string {
	if name[len(name)-1:] != "*" {
		name = name + "*"
	}

	return name
}

// translatePoliciesToExceptions takes a Kyverno ClusterPolicy array and transforms it into a Kyverno Exception array
func translatePoliciesToExceptions(policies []kyvernov1.ClusterPolicy) []kyvernov2.Exception {
	var exceptionArray []kyvernov2.Exception
	for _, kyvernoPolicy := range policies {
		kyvernoException := kyvernov2.Exception{
			PolicyName: kyvernoPolicy.Name,
			RuleNames:  generatePolicyRules(kyvernoPolicy),
		}
		exceptionArray = append(exceptionArray, kyvernoException)
	}

	return exceptionArray
}

// generatePolicyRules takes a Kyverno Policy name and generates a list of rules owned by that policy
func generatePolicyRules(kyvernoPolicy kyvernov1.ClusterPolicy) []string {
	var rulesArray []string
	for _, rule := range kyvernoPolicy.Spec.Rules {
		rulesArray = append(rulesArray, rule.Name)
	}
	for _, autogenRule := range kyvernoPolicy.Status.Autogen.Rules {
		rulesArray = append(rulesArray, autogenRule.Name)
	}

	return rulesArray
}

// unorderedEqual takes two Kyverno Exception arrays and checks if they are equal even if they are not ordered the same
func unorderedEqual(got, want []kyvernov2.Exception) bool {
	// Check Length size first
	if len(got) != len(want) {
		return false
	}
	// Create an exceptions map with the new desired Exceptions
	exceptionMap := make(map[string][]string)
	for _, exception := range want {
		exceptionMap[exception.PolicyName] = exception.RuleNames
	}
	for _, exception := range got {
		// Check if the Policy Name is still present in the new Exceptions
		if _, exists := exceptionMap[exception.PolicyName]; !exists {
			// The Policy is not present in the new array
			// Arrays are not equals, exit
			return false
		} else {
			// Check if the same RuleNames are still present in the new Exceptions
			for _, oldRule := range exception.RuleNames {
				found := false
				// Check against every rule, exit if found
				for _, newRule := range exceptionMap[exception.PolicyName] {
					if newRule == oldRule {
						// Found, break for
						found = true
						break
					}
				}
				if !found {
					// The arrays are not equals, exit
					return false
				}
				// Rules are equals, continue
			}
		}
	}
	// Arrays are equals
	return true
}
