version: 2.1
orbs:
  architect: giantswarm/architect@4.33.0

workflows:
  package-and-push-chart-on-tag:
    jobs:
      - architect/go-build:
          name: go-build
          binary: kyverno-policy-operator
          resource_class: large
          filters:
            tags:
              only: /^v.*/

      - architect/push-to-docker:
          context: "architect"
          name: push-kyverno-policy-operator-to-docker
          image: "docker.io/giantswarm/kyverno-policy-operator"
          username_envar: "DOCKER_USERNAME"
          password_envar: "DOCKER_PASSWORD"
          requires:
            - go-build
          # Needed to trigger job also on git tag.
          filters:
            tags:
              only: /^v.*/

      - architect/push-to-docker:
          context: "architect"
          name: push-kyverno-policy-operator-to-quay
          image: "quay.io/giantswarm/kyverno-policy-operator"
          username_envar: "QUAY_USERNAME"
          password_envar: "QUAY_PASSWORD"
          requires:
            - go-build
          # Needed to trigger job also on git tag.
          filters:
            tags:
              only: /^v.*/

      - architect/push-to-docker:
          context: "architect"
          name: push-kyverno-policy-operator-to-aliyun
          image: "giantswarm-registry.cn-shanghai.cr.aliyuncs.com/giantswarm/kyverno-policy-operator"
          username_envar: "ALIYUN_USERNAME"
          password_envar: "ALIYUN_PASSWORD"
          requires:
            - go-build
          # Needed to trigger job also on git tag.
          filters:
            tags:
              only: /^v.*/

      # Push to App catalogs
      - architect/push-to-app-catalog:
          context: "architect"
          executor: "app-build-suite"
          name: "package and push kyverno-policy-operator chart"
          app_catalog: "giantswarm-catalog"
          app_catalog_test: "giantswarm-test-catalog"
          chart: "kyverno-policy-operator"
          # Trigger job on git tag.
          filters:
            tags:
              only: /^v.*/

      - architect/push-to-app-catalog:
          context: "architect"
          executor: "app-build-suite"
          name: push-kyverno-policy-operator-chart-to-control-plane-catalog
          app_catalog: "control-plane-catalog"
          app_catalog_test: "control-plane-test-catalog"
          chart: "kyverno-policy-operator"
          # Trigger job on git tag.
          filters:
            tags:
              only: /^v.*/
      
      # Push to collections
      - architect/push-to-app-collection:
          name: aws-app-collection
          context: "architect"
          app_name: "kyverno-policy-operator"
          app_collection_repo: "aws-app-collection"
          requires:
            - push-kyverno-policy-operator-chart-to-control-plane-catalog
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/

      - architect/push-to-app-collection:
          name: azure-app-collection
          context: "architect"
          app_name: "kyverno-policy-operator"
          app_collection_repo: "azure-app-collection"
          requires:
            - push-kyverno-policy-operator-chart-to-control-plane-catalog
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/

      - architect/push-to-app-collection:
          name: capa-app-collection
          context: "architect"
          app_name: "kyverno-policy-operator"
          app_collection_repo: "capa-app-collection"
          requires:
            - push-kyverno-policy-operator-chart-to-control-plane-catalog
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/

      - architect/push-to-app-collection:
          name: capz-app-collection
          context: "architect"
          app_name: "kyverno-policy-operator"
          app_collection_repo: "capz-app-collection"
          requires:
            - push-kyverno-policy-operator-chart-to-control-plane-catalog
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/

      - architect/push-to-app-collection:
          name: gcp-app-collection
          context: "architect"
          app_name: "kyverno-policy-operator"
          app_collection_repo: "gcp-app-collection"
          requires:
            - push-kyverno-policy-operator-chart-to-control-plane-catalog
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/

      - architect/push-to-app-collection:
          name: vsphere-app-collection
          context: "architect"
          app_name: "kyverno-policy-operator"
          app_collection_repo: "vsphere-app-collection"
          requires:
            - push-kyverno-policy-operator-chart-to-control-plane-catalog
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/

      - architect/push-to-app-collection:
          name: cloud-director-app-collection
          context: "architect"
          app_name: "kyverno-policy-operator"
          app_collection_repo: "cloud-director-app-collection"
          requires:
            - push-kyverno-policy-operator-chart-to-control-plane-catalog
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
