version: 2.1
orbs:
  architect: giantswarm/architect@6.7.0

jobs:
  unit-tests:
    executor: architect/architect
    steps:
    - checkout
    - run:
        name: Run unit tests
        command: CGO_ENABLED=0 make test-unit

workflows:
  package-and-push-chart-on-tag:
    jobs:
    - unit-tests:
        filters:
          tags:
            only: /^v.*/

    - architect/go-build:
        name: go-build
        binary: kyverno-policy-operator
        resource_class: large
        filters:
          tags:
            only: /^v.*/

    - architect/push-to-registries:
        context: architect
        name: push-to-registries
        requires:
        - go-build
        filters:
          tags:
            only: /^v.*/

          branches:
            ignore:
            - main
            - master
    - architect/push-to-app-catalog:
        context: architect
        executor: app-build-suite
        name: package and push kyverno-policy-operator chart
        app_catalog: giantswarm-catalog
        app_catalog_test: giantswarm-test-catalog
        chart: kyverno-policy-operator
        requires:
        - push-to-registries
        filters:
          tags:
            only: /^v.*/

          branches:
            ignore:
            - main
            - master
    - architect/push-to-app-catalog:
        context: architect
        executor: app-build-suite
        name: push-kyverno-policy-operator-chart-to-control-plane-catalog
        app_catalog: control-plane-catalog
        app_catalog_test: control-plane-test-catalog
        chart: kyverno-policy-operator
        requires:
        - push-to-registries
        filters:
          tags:
            only: /^v.*/

      # Push to collections
          branches:
            ignore:
            - main
            - master
