version: 2.1
orbs:
  architect: giantswarm/architect@5.4.0

workflows:
  package-and-push-chart-on-tag:
    jobs:
      - architect/go-build:
          name: go-build
          binary: kyverno-policy-operator
          resource_class: large
          filters:
            tags:
              only: /^v.*/

      - architect/push-to-registries:
          context: architect
          name: push-to-registries
          requires:
            - go-build
          filters:
            tags:
              only: /^v.*/

      - architect/push-to-app-catalog:
          context: "architect"
          executor: "app-build-suite"
          name: "package and push kyverno-policy-operator chart"
          app_catalog: "giantswarm-catalog"
          app_catalog_test: "giantswarm-test-catalog"
          chart: "kyverno-policy-operator"
          requires:
            - push-to-registries
          filters:
            tags:
              only: /^v.*/

      - architect/push-to-app-catalog:
          context: "architect"
          executor: "app-build-suite"
          name: push-kyverno-policy-operator-chart-to-control-plane-catalog
          app_catalog: "control-plane-catalog"
          app_catalog_test: "control-plane-test-catalog"
          chart: "kyverno-policy-operator"
          requires:
            - push-to-registries
          filters:
            tags:
              only: /^v.*/

      # Push to collections
      - architect/push-to-app-collection:
          name: aws-app-collection
          context: "architect"
          app_name: "kyverno-policy-operator"
          app_collection_repo: "aws-app-collection"
          requires:
            - push-kyverno-policy-operator-chart-to-control-plane-catalog
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/

      - architect/push-to-app-collection:
          name: azure-app-collection
          context: "architect"
          app_name: "kyverno-policy-operator"
          app_collection_repo: "azure-app-collection"
          requires:
            - push-kyverno-policy-operator-chart-to-control-plane-catalog
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
