---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - policy.giantswarm.io.giantswarm.io
  resources:
  - policyexceptiondrafts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - policy.giantswarm.io.giantswarm.io
  resources:
  - policyexceptiondrafts/finalizers
  verbs:
  - update
- apiGroups:
  - policy.giantswarm.io.giantswarm.io
  resources:
  - policyexceptiondrafts/status
  verbs:
  - get
  - patch
  - update
