name: kyverno-policy-operator
serviceType: managed

image:
  registry: gsoci.azurecr.io
  name: giantswarm/kyverno-policy-operator
  pullPolicy: IfNotPresent

# Install PSPs
global:
  image:
    registry: "gsoci.azurecr.io"
  # Enable PSPs
  podSecurityStandards:
    enforced: false

ciliumNetworkPolicy:
  enabled: true

# We install CRDs through a Job with the helm specific crd folder.
crds:
  install: true
  image:
    tag: "1.27.4"
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 200m
      memory: 512Mi

nodeSelector: {}
tolerations: []

# Additional custom pod labels
podLabels: {}

# Pod securityContext
podSecurityContext:
  runAsUser: 1000
  runAsGroup: 1000
  runAsNonRoot: true
  readOnlyRootFilesystem: true
  seccompProfile:
    type: RuntimeDefault

# Container securityContext
containerSecurityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  privileged: false
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  seccompProfile:
    type: RuntimeDefault

resources:
  requests:
    cpu: 100m
    memory: 220Mi
  limits:
    cpu: 100m
    memory: 220Mi

policyOperator:
  # Set where to install PolicyExceptions
  destinationNamespace: "policy-exceptions"
  # Apply the generated PolicyExceptions also in Kyverno background scans. Changes audit results from fail to skip.
  exceptionBackgroundMode: true
  chartOperatorExcemptedKinds:
    - PolicyException
    - Namespace
