{{- if .Values.ciliumNetworkPolicy.enabled }}
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: {{ include "resource.default.name"  . }}
  namespace: {{ include "resource.default.namespace"  . }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
spec:
  endpointSelector:
    matchLabels:
      {{- include "labels.selector" . | nindent 6 }}
  egress:
    - toEntities:
        - kube-apiserver
    - toEndpoint:
        - matchLabels:
            app.kubernetes.io/name: edgedb
            app.kubernetes.io/instance: edgedb
      toPorts:
        - ports:
            - port: "5656"
              protocol: TCP
  ingress:
    - fromEntities:
        - kube-apiserver
{{- end }}
