apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kyverno-policy-operator.crdAdoption" . }}
  namespace: {{ .Release.Namespace }}
  annotations:
    # create hook dependencies in the right order
    "helm.sh/hook-weight": "-4"
    {{- include "kyverno-policy-operator.crdAdoptionAnnotations" . | nindent 4 }}
  labels:
    app.kubernetes.io/component: {{ include "kyverno-policy-operator.crdAdoption" . | quote }}
    {{- include "labels.selector" . | nindent 4 }}
    role: {{ include "kyverno-policy-operator.crdAdoptionSelector" . | quote }}
