apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kyverno-policy-operator.crdAdoption" . }}
  namespace: {{ .Release.Namespace | quote }}
  annotations:
    # create hook dependencies in the right order
    "helm.sh/hook-weight": "-3"
    {{- include "kyverno-policy-operator.crdAdoptionAnnotations" . | nindent 4 }}
  labels:
    app.kubernetes.io/component: {{ include "kyverno-policy-operator.crdAdoption" . | quote }}
    {{- include "labels.selector" . | nindent 4 }}
    role: {{ include "kyverno-policy-operator.crdAdoptionSelector" . | quote }}
rules:
- apiGroups:
  - ""
  resources:
  - jobs
  verbs:
  - create
  - delete
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - get
  - patch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "kyverno-policy-operator.crdAdoption" . }}
  namespace: {{ .Release.Namespace | quote }}
  annotations:
    # create hook dependencies in the right order
    "helm.sh/hook-weight": "-2"
    {{- include "kyverno-policy-operator.crdAdoptionAnnotations" . | nindent 4 }}
  labels:
    app.kubernetes.io/component: {{ include "kyverno-policy-operator.crdAdoption" . | quote }}
    {{- include "labels.common" . | nindent 4 }}
    role: {{ include "kyverno-policy-operator.crdAdoptionSelector" . | quote }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "kyverno-policy-operator.crdAdoption" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "kyverno-policy-operator.crdAdoption" . }}
    namespace: {{ .Release.Namespace | quote }}
